export const shopCategories = [
  { value: "mens_clothing", label: "Men's Clothing" },
  { value: "womens_clothing", label: "Women's Clothing" },
  { value: "kids_baby_clothing", label: "Kids & Baby Clothing" },
  { value: "shoes_footwear", label: "Shoes & Footwear" },
  { value: "jewelry_accessories", label: "Jewelry & Accessories" },
  { value: "handbags_wallets", label: "Handbags & Wallets" },
  { value: "watches", label: "Watches" },
  { value: "eyewear", label: "Eyewear" },
  { value: "lingerie_sleepwear", label: "Lingerie & Sleepwear" },
  { value: "hats_caps", label: "Hats & Caps" },

  { value: "mobile_phones", label: "Mobile Phones" },
  { value: "laptops_computers", label: "Laptops & Computers" },
  { value: "tablets", label: "Tablets" },
  { value: "gaming_consoles", label: "Gaming Consoles" },
  { value: "cameras_photography", label: "Cameras & Photography" },
  { value: "headphones_earbuds", label: "Headphones & Earbuds" },
  { value: "smartwatches_wearables", label: "Smartwatches & Wearables" },
  { value: "tvs_home_theater", label: "TVs & Home Theater" },
  { value: "home_appliances", label: "Home Appliances" },
  { value: "computer_accessories", label: "Computer Accessories" },

  { value: "skincare", label: "Skincare" },
  { value: "haircare", label: "Haircare" },
  { value: "makeup_cosmetics", label: "Makeup & Cosmetics" },
  { value: "fragrances", label: "Fragrances" },
  { value: "personal_care", label: "Personal Care" },
  { value: "health_supplements", label: "Health Supplements" },
  { value: "medical_supplies", label: "Medical Supplies" },
  { value: "fitness_equipment", label: "Fitness Equipment" },

  { value: "furniture", label: "Furniture" },
  { value: "bedding_bath", label: "Bedding & Bath" },
  { value: "home_decor", label: "Home Decor" },
  { value: "lighting", label: "Lighting" },
  { value: "kitchenware", label: "Kitchenware" },
  { value: "storage_organization", label: "Storage & Organization" },
  { value: "cleaning_supplies", label: "Cleaning Supplies" },
  { value: "smart_home_devices", label: "Smart Home Devices" },

  { value: "fruits_vegetables", label: "Fruits & Vegetables" },
  { value: "snacks_packaged_foods", label: "Snacks & Packaged Foods" },
  { value: "beverages", label: "Beverages" },
  { value: "meat_seafood", label: "Meat & Seafood" },
  { value: "dairy_eggs", label: "Dairy & Eggs" },
  { value: "bakery_bread", label: "Bakery & Bread" },
  { value: "organic_health_foods", label: "Organic & Health Foods" },
  { value: "condiments_spices", label: "Condiments & Spices" },

  { value: "exercise_fitness", label: "Exercise & Fitness" },
  { value: "camping_hiking", label: "Camping & Hiking" },
  { value: "cycling", label: "Cycling" },
  { value: "team_sports", label: "Team Sports" },
  { value: "water_sports", label: "Water Sports" },
  { value: "winter_sports", label: "Winter Sports" },
  { value: "sportswear", label: "Sportswear" },
  { value: "outdoor_furniture", label: "Outdoor Furniture" },

  { value: "baby_clothing", label: "Baby Clothing" },
  { value: "toys_games", label: "Toys & Games" },
  { value: "strollers_car_seats", label: "Strollers & Car Seats" },
  { value: "feeding_nursing", label: "Feeding & Nursing" },
  { value: "diapers_potty", label: "Diapers & Potty" },
  { value: "nursery_furniture", label: "Nursery Furniture" },
  { value: "educational_toys", label: "Educational Toys" },

  { value: "books", label: "Books" },
  { value: "magazines", label: "Magazines" },
  { value: "notebooks_diaries", label: "Notebooks & Diaries" },
  { value: "pens_writing_instruments", label: "Pens & Writing Instruments" },
  { value: "school_supplies", label: "School Supplies" },
  { value: "art_craft_supplies", label: "Art & Craft Supplies" },
  { value: "calendars_planners", label: "Calendars & Planners" },

  { value: "car_parts_accessories", label: "Car Parts & Accessories" },
  { value: "motorcycles_scooters", label: "Motorcycles & Scooters" },
  { value: "car_electronics", label: "Car Electronics" },
  { value: "car_maintenance", label: "Car Care & Maintenance" },
  { value: "oils_fluids", label: "Oils & Fluids" },
  { value: "tools_equipment", label: "Tools & Equipment" },

  { value: "pet_food", label: "Pet Food" },
  { value: "pet_toys", label: "Pet Toys" },
  { value: "pet_grooming", label: "Pet Grooming" },
  { value: "pet_health_supplies", label: "Pet Health Supplies" },
  { value: "aquarium_supplies", label: "Aquarium Supplies" },
  { value: "pet_furniture", label: "Pet Beds & Furniture" },

  { value: "power_tools", label: "Power Tools" },
  { value: "hand_tools", label: "Hand Tools" },
  { value: "building_materials", label: "Building Materials" },
  { value: "paint_supplies", label: "Paint & Supplies" },
  { value: "plumbing", label: "Plumbing" },
  { value: "electricals", label: "Electricals" },
  { value: "gardening_tools", label: "Gardening Tools" },

  { value: "musical_instruments", label: "Musical Instruments" },
  { value: "board_games", label: "Board Games" },
  { value: "video_games", label: "Video Games" },
  { value: "movies_dvds", label: "Movies & DVDs" },
  { value: "collectibles", label: "Collectibles" },
  { value: "posters_art_prints", label: "Posters & Art Prints" },

  { value: "salon_spa_services", label: "Salon & Spa Services" },
  { value: "home_cleaning_services", label: "Home Cleaning Services" },
  { value: "pet_grooming_services", label: "Pet Grooming Services" },
  { value: "tailoring_alteration", label: "Tailoring & Alteration" },
  { value: "printing_services", label: "Printing Services" },
  { value: "repair_services", label: "Repair Services" },

  { value: "suitcases_trolleys", label: "Suitcases & Trolleys" },
  { value: "backpacks", label: "Backpacks" },
  { value: "travel_accessories", label: "Travel Accessories" },
  { value: "travel_guides", label: "Travel Guides & Books" },

  { value: "greeting_cards", label: "Greeting Cards" },
  { value: "gift_sets", label: "Gift Sets" },
  { value: "party_supplies", label: "Party Supplies" },
  { value: "wedding_essentials", label: "Wedding Essentials" },
  { value: "festive_decorations", label: "Festive Decorations" },

  { value: "safety_equipment", label: "Safety Equipment" },
  { value: "packaging_supplies", label: "Packaging Supplies" },
  { value: "office_equipment", label: "Office Equipment" },
  { value: "industrial_tools", label: "Industrial Tools" },
  { value: "wholesale_products", label: "Wholesale Products" },

  { value: "antiques", label: "Antiques" },
  { value: "thrift_secondhand", label: "Thrift & Secondhand" },
  { value: "subscription_boxes", label: "Subscription Boxes" },
  { value: "virtual_products", label: "Virtual Products" },
  { value: "nft_digital_art", label: "NFT & Digital Art" },
];
